plugins {
    id("java-library")
    id("maven-publish")
}

// configure project dependency repos
// mod loader plugins may automatically provide others
repositories {
    mavenLocal()
    mavenCentral()

    exclusiveContent {
        forRepository {
            //noinspection ForeignDelegate
            maven {
                name = "ParchmentMC"
                url = uri("https://maven.parchmentmc.org")
            }
        }
        filter {
            includeGroup("org.parchmentmc.data")
        }
    }

    maven {
        name = "Modrinth"
        url = uri("https://api.modrinth.com/maven")
    }

    maven {
        name = "CurseForge"
        url = uri("https://cursemaven.com")
    }

    // add property-defined repos
    safeList("dep_repos").each { String $repo ->
        try {
            final String[] $repoData = get("dep_repo_${$repo}").split(":")
            final String $repoUrl = $repoData[0]
            final String $repoFilter = $repoData.length > 1 ? $repoData[1] : "-"

            if ($repoFilter == "-") {
                // unfiltered
                maven {
                    name = $repo
                    url = uri("https://${$repoUrl}")
                }
            } else {
                // filtered
                exclusiveContent {
                    forRepository {
                        //noinspection ForeignDelegate
                        maven {
                            name = $repo
                            url = uri("https://${$repoUrl}")
                        }
                    }
                    filter {
                        includeGroupAndSubgroups($repoFilter)
                    }
                }
            }
        } catch (Exception $e) {
            logger.error("Error processing maven repository '${$repo}'. Check property format.")
            throw $e
        }
    }
}

// set output file name
base {
    archivesName = "${mod_id}-${project.name}"
}

// configure Java build
java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    if (build_sources_jar == "true") withSourcesJar()
    if (build_javadoc_jar == "true") withJavadocJar()
}

// declare capabilities on the outgoing configurations
final List<String> $capabilityVariants = ["apiElements", "runtimeElements"]
if (build_sources_jar == "true") $capabilityVariants.add("sourcesElements")
if (build_javadoc_jar == "true") $capabilityVariants.add("javadocElements")
$capabilityVariants.each { String $variant ->
    configurations.named($variant).configure {
        outgoing {
            capability("$group:${base.archivesName.get()}:$version")
            capability("$group:$mod_id:$version")
        }
    }
}

// configure main jar
jar {
    from(rootProject.file("LICENSE.txt")) {
        rename { "LICENSE_${mod_id}.txt" }
    }

    manifest {
        attributes([
                "Specification-Title"     : mod_name,
                "Specification-Vendor"    : mod_owner,
                "Specification-Version"   : project.jar.archiveVersion,
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : mod_owner,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "Timestamp"               : System.currentTimeMillis(),
                "Built-On-Java"           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                "Built-On-Minecraft"      : minecraft_version
        ])
    }
}

// configure sources jar
if (build_sources_jar == "true") {
    sourcesJar {
        from(rootProject.file("LICENSE.txt")) {
            rename { "LICENSE_${mod_id}.txt" }
        }
    }
}

// process Gradle property expansion for metadata files
processResources {
    final LinkedHashMap<String, String> $expandProps = [
            // Mod
            "mod_version"                : mod_version,
            "mod_group"                  : mod_group,
            "mod_id"                     : mod_id,
            "mod_name"                   : mod_name,
            "mod_description_fabric"     : mod_description.replace("\n", "\\n"),
            "mod_description_neoforge"   : mod_description,
            "mod_icon"                   : "assets/${mod_id}/icon.png",
            "mod_owner"                  : mod_owner,
            "mod_authors_list"           : asJsonList(mod_authors),
            "mod_authors_string"         : mod_authors.split(",").join(", "),
            "mod_contributors_list"      : asJsonList("${mod_contributors},${mod_translators},${mod_credits}"),
            "mod_contributors_string"    : asTomlList("${mod_contributors},${mod_translators},${mod_credits}"),
            "mod_license"                : mod_license,
            // Links
            "homepage_url"               : homepage_url,
            "sources_url"                : sources_url,
            "issues_url"                 : issues_url,
            "contact_url"                : contact_url,
            // Java
            "java_version"               : java_version,
            "java_versions_fabric_list"  : asJsonList(java_versions_fabric),
            "java_versions_neoforge"     : java_versions_neoforge,
            // Minecraft
            "minecraft_versions_fabric_list": asJsonList(minecraft_versions_fabric),
            "minecraft_versions_neoforge": minecraft_versions_neoforge,
            // Mixin
            "mixin_version_min"          : mixin_version_min,
            "mixinextras_version_min"    : mixinextras_version_min,
            // Fabric
            "fabric_loader_versions_list": asJsonList(fabric_loader_versions),
            "fabric_api_versions_list"   : asJsonList(fabric_api_versions),
            "fabric_environment"         : fabric_environment,
            "fabric_entrypoints_main"    : asJsonListPrefixed(fabric_entrypoints_main, "${mod_group}.${mod_id}."),
            "fabric_entrypoints_client"  : asJsonListPrefixed(fabric_entrypoints_client, "${mod_group}.${mod_id}."),
            "fabric_entrypoints_server"  : asJsonListPrefixed(fabric_entrypoints_server, "${mod_group}.${mod_id}."),
            "fabric_entrypoints_modmenu" : asJsonListPrefixed(fabric_entrypoints_modmenu, "${mod_group}.${mod_id}."),
            // NeoForge
            "neoforge_versions"          : neoforge_versions,
            // Dependencies:
            "fabric_depends"             : "",
            "fabric_recommends"          : "",
            "fabric_suggests"            : "",
            "fabric_conflicts"           : "",
            "fabric_breaks"              : "",
            "neoforge_all_deps"          : ""
    ]

    // add Fabric-specific property expansions
    safeList("fabric_deps").each { $dep ->
        try {
            final String[] $depData = list("d_fabric_${$dep}")
            if ($depData.length > 1 && $depData[1] != "-") {
                final String[] $loaderData = $depData[1].split(":")
                final String $key = "fabric_${$loaderData[0]}".toString()
                final String $prefix = $expandProps[$key] == "" ? "" : ",\n    "
                final String $depList = "[${asJsonList(project.property("vr_fabric_${$dep}").toString())}]"
                final String $value = "${$expandProps[$key]}${$prefix}\"${$loaderData[1]}\": ${$depList}"
                $expandProps[$key] = $value.toString()
                logger.trace("Fabric metadata '${$key}': ${$expandProps[$key]}")
            }
        } catch (Exception $e) {
            logger.error("Error processing Fabric dependency metadata for '${$dep}'. Check dependency property format.")
            throw $e
        }
    }
    if (!$expandProps["fabric_depends"].isBlank()) {
        $expandProps["fabric_depends"] = "${$expandProps["fabric_depends"]},".toString()
    }

    // add NeoForge-specific property expansions
    safeList("neoforge_deps").each { String $dep ->
        try {
            final String[] $depData = list("d_neoforge_${$dep}")
            if ($depData.length > 1 && $depData[1] != "-") {
                final String[] $loaderData = $depData[1].split(":")
                $expandProps["neoforge_all_deps"] = $expandProps["neoforge_all_deps"] +
                        "[[dependencies.${mod_id}]]\n" +
                        "modId=\"${$loaderData[1]}\"\n" +
                        "type=\"${$loaderData[0]}\"\n" +
                        "versionRange=\"${project.property("vr_neoforge_${$dep}")}\"\n" +
                        "side=\"BOTH\"\n\n"
            }
        } catch (Exception $e) {
            logger.error("Error processing NeoForge dependency metadata for '${$dep}'. Check dependency property format.")
            throw $e
        }
    }
    logger.trace("NeoForge metadata 'neoforge_all_deps': ${$expandProps["neoforge_all_deps"]}")

    // apply expansion to metadata files
    filesMatching(["pack.mcmeta", "*.mod.json", "*.mixins.json", "META-INF/*.toml"]) {
        expand($expandProps)
    }
    inputs.properties($expandProps)
}

// configure maven publishing
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from(components.java)
        }
    }
}

/**
 * Converts a CSV list into an FMJ-usable format.
 */
static asJsonList(String $csvString) {
    return $csvString.split(",")
            .findAll { !it.isBlank() }
            .collect { "\"${it.strip()}\"" }
            .join(",")
}

/**
 * Converts a CSV list into an FMJ-usable list format, prefixing each element with the source
 * package (${mod_group}.${mod_id}).
 */
static asJsonListPrefixed(String $csvString, String $prefix) {
    return $csvString.split(",")
            .findAll { !it.isBlank() }
            .collect { "\"${$prefix}${it.strip()}\"" }
            .join(",")
}

/**
 * Converts a CSV list into an NMT-usable format.
 */
static asTomlList(String $csvString) {
    return $csvString.split(",")
            .findAll { !it.isBlank() }
            .collect { it.strip() }
            .join(", ")
}

/**
 @return {@code true} if the property is set.
 */
boolean has(String $propertyName) {
    return project.hasProperty($propertyName) && !get($propertyName).toString().isBlank()
}

/**
 @return the value of the property.
 */
String get(String $propertyName) {
    return project.property($propertyName)
}

/**
 @return the value of the property if it exists, an empty string otherwise.
 */
String safe(String $propertyName) {
    return has($propertyName) ? get($propertyName) : ""
}

/**
 @return the value of the property, CSV-split.
 */
String[] list(String $propertyName) {
    return get($propertyName).toString().split(",")
            .findAll { !it.isBlank() }
            .collect { it.strip() }
}

/**
 @return the value of the property CSV-split if it is set, an empty array otherwise.
 */
String[] safeList(String $propertyName) {
    return has($propertyName) ? list($propertyName) : []
}
