modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Scotsguy/now-playing/issues"
license="MIT"

[[mods]]
modId="nowplaying"
version="${file.jarVersion}"
displayName="Now Playing"
displayURL="https://github.com/Scotsguy/now-playing"
logoFile="nowplaying.png"
credits="Thanks to the Forge Team for their work"
authors="AppleTheGolden, JayJay1989BE"
description="Shows a 'now playing' popup whenever a song starts to play."

[[dependencies.nowplaying]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.nowplaying]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="CLIENT"