on:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - '*'
  pull_request:

name: Build Mod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          gradle-version: wrapper
          arguments: build --stacktrace
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar
